spring:
  application:
    name: ms-personal
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070
  main:
    allow-bean-definition-overriding: true